id: P3D7A3DA2
initial_creation_type: input
source_metadata:
  title: Prophecy Series
  language: en
  description: 'A selection of texts on the theme of prophecy or predictions (Skt.
    vyākaraṇa; Tib. lung bstan):'
  volume:
    91e1bbfbf0574d18b82a21d1359ed588:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Terma
    1b819f79de0049b388a9bf595fcae9f2:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Terma
    6b0c52c7213348be92b309754546a31e:
      title: 'The Clarifying Light: A Prophecy of the Future'
      parent: Words of the Buddha
created_at: '2022-03-01T05:24:04.311351'
last_modified_at: '2022-03-01T05:24:04.311361'
